# Generated by Django 2.2.8 on 2020-10-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201005_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discription',
            field=models.TextField(default='This is a test discription and lets see if this works or not'),
            preserve_default=False,
        ),
    ]
