# Generated by Django 3.1.6 on 2021-06-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210607_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='esewa_charge_id',
            field=models.CharField(max_length=500),
        ),
    ]
